
language: java
jdk:
  - openjdk16
services:
  - docker

before_install:
  - docker pull adoptopenjdk/openjdk16:alpine-jre

script:
  - ./gradlew test
  - ./gradlew build

deploy:
  provider: heroku
  app: assessment-platform
  api_key: $HEROKU_API_KEY
  on:
    branch: master
