
language: java
jdk:
  - openjdk16
services:
  - docker

before_install:
  - docker pull adoptopenjdk/openjdk16:alpine-jre

script:
  - ./gradlew test
  - ./gradlew build

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "AssessmentServer"
  env: "Assessmentserver-env"
  bucket-name: "elasticbeanstalk-us-east-1-639392862171"
  bucket-path: "AssessmentServer"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY