version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=assessment
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=fmIZ3REf
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  assessment:
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres/assessment
      - JDBC_DATABASE_USERNAME=admin
      - JDBC_DATABASE_PASSWORD=fmIZ3REf
    build: .
    depends_on:
      - postgres