version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=assessment
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=fmIZ3REf
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'
  assessment:
    environment:
      - PGURL=jdbc:postgresql://postgres/assessment
      - PGUSER=admin
      - PGPASSWORD=fmIZ3REf
    build: .
    depends_on:
      - postgres